#if 0
# This file is generated by cbindgen. DO NOT EDIT
#endif


public partial class Functions {
  [DllImport("bindgen.dll")]
  public static extern void root();
}

#if 0
# This is a simple test to ensure that trailers do not cause extra newlines in files
#endif
